'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Redux provider and store
import { Provider } from "react-redux";
import { store } from "./redux/store"; // Path to your Redux store

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the children with Redux Provider */}
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
